# Generated by Django 5.0.7 on 2025-05-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('generaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.generaluser')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=100)),
                ('messagingHistory', models.TextField(blank=True)),
                ('buyingHistory', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('telNumber', models.FloatField()),
                ('likedAds', models.ManyToManyField(blank=True, related_name='liked_by', to='ads.ad')),
            ],
            bases=('user.generaluser',),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.member')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('user.member',),
        ),
    ]
