# Generated by Django 5.2.1 on 2025-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
