# Generated by Django 5.0.7 on 2025-05-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('barganing', models.BooleanField(default=False)),
                ('adDate', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('likedRate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.ad')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('productionYear', models.DateField()),
                ('millage', models.FloatField()),
                ('transmission', models.BooleanField(default=True)),
                ('fuelType', models.CharField(max_length=50)),
            ],
            bases=('ads.ad',),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('ad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.ad')),
                ('type', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
            ],
            bases=('ads.ad',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('ad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.ad')),
                ('rooms', models.IntegerField()),
                ('size_m2', models.FloatField()),
                ('floor', models.IntegerField()),
                ('buildYear', models.IntegerField()),
            ],
            bases=('ads.ad',),
        ),
    ]
