# Generated by Django 5.0 on 2025-05-03 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('bargaining', models.BooleanField(default=False)),
                ('adDate', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('likedRate', models.FloatField(default=0)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('productionYear', models.DateField()),
                ('millage', models.FloatField()),
                ('transmission', models.BooleanField()),
                ('fuelType', models.CharField(max_length=50)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='likedCars', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('bargaining', models.BooleanField(default=False)),
                ('adDate', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('likedRate', models.FloatField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='likedFurnitures', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('comments', models.TextField(blank=True)),
                ('bargaining', models.BooleanField(default=False)),
                ('adDate', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('likedRate', models.FloatField(default=0)),
                ('rooms', models.IntegerField()),
                ('size_m2', models.FloatField()),
                ('floor', models.IntegerField()),
                ('buildYear', models.IntegerField()),
                ('liked_by', models.ManyToManyField(blank=True, related_name='likedHouses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
