# Generated by Django 5.0.7 on 2025-05-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
