# Generated by Django 5.0.7 on 2025-05-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
    ]
